#!/bin/sh
echo "Blackroo Linux starting..."
mount -t proc none /proc 2>/dev/null
mount -t sysfs none /sys 2>/dev/null
echo ""
echo "  ____  _            _                    "
echo " | __ )| | __ _  ___| | ___ __ ___   ___  "
echo " |  _ \\| |/ _\` |/ __| |/ / '__/ _ \\ / _ \\ "
echo " | |_) | | (_| | (__|   <| | | (_) | (_) |"
echo " |____/|_|\\__,_|\\___|_|\\_\\_|  \\___/ \\___/ "
echo "              Linux for PlayStation"
echo ""
echo "Welcome to Blackroo Linux!"
echo "Type 'busybox' to see available commands."
echo ""
