[platformio]
src_dir = main

[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_type = debug

lib_deps =
    m5stack/M5Unified

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_S3_PS1_RX_GPIO=44
    -D CORE_S3_PS1_TX_GPIO=43
    -D CORE_S3_PS1_BAUD=115200

board_build.cmake_extra_args =
    -D SDKCONFIG_DEFAULTS=sdkconfig.defaults
